spring.datasource.url=jdbc:postgresql://db.mxttrgrvlpcxyjbpgzre.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=q5J._paC&SB7!TR
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
gemini.api.key=your_gemini_api_key_here
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent